version: "3.9"

services: 
  db:
    image: postgres:13-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env

volumes:
  dev-db-data:
