version: "3.9"

services: 
  db:
    image: postgres:13-alpine
    volumes:
      - /home/luis/projects/database/postgres/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

volumes:
  dev-db-data:
